# Generated by Django 2.2.17 on 2020-11-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('comment', models.TextField()),
                ('sentiment', models.FloatField()),
                ('comment_time', models.DateField()),
            ],
        ),
    ]
