# Generated by Django 2.2.13 on 2020-09-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('star', models.IntegerField(verbose_name=11)),
                ('comment', models.TextField()),
                ('comment_time', models.DateField()),
            ],
        ),
    ]
